### ISSUE TITLE
getinput(0).shape wrong

### ISSUE THREAD

**Issue by jamesfff** [KopiSoftware/TRT_Ultra_Fast_Lane_Detect#1]
Loading ONNX file from path model.pth...
Traceback (most recent call last):
  File "onnx_to_tensorrt.py", line 84, in <module>
    main()
  File "onnx_to_tensorrt.py", line 76, in main
    engine = build_engine(onnx_file_path, mode,args.verbose)
  File "onnx_to_tensorrt.py", line 40, in build_engine
    shape = list(network.get_input(0).shape)
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by jamesfff** [comment]
my mistake , I have solved it , sorry

**Comment by sevgiserra** [comment]
I am facing the same problem, could you please tell me how you solved it? Thank you.
